leftnav:
- identifier: 8d7f0c29-ba10-3259-7441-c2790cf9b47a
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 4e5c1575-20bb-d074-4a4b-c0abcd17099d
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: 1c62f712-bf1c-b829-37d1-4ea86c3b8672
  name: Readings
  url: /pages/readings
  weight: 30
- identifier: 452642f2-dc9f-9093-87c9-7c046705b92a
  name: Lectures
  url: /pages/lectures
  weight: 40
- identifier: 5d1a5094-f9b1-d4d4-bff1-91eb06deeed4
  name: Assignments
  url: /pages/assignments
  weight: 50
- identifier: 4121d094-5294-dd04-7363-d91b0b145ceb
  name: Exams
  url: /pages/exams
  weight: 60
- identifier: 4d671211-55ab-38ce-b99f-69217d1fa9a0
  name: Related Resources
  url: /pages/related-resources
  weight: 70
